### ISSUE TITLE
いいところ診断の結果に優しさを追加したい

### ISSUE THREAD

**Issue by anoriqq** [anoriqq/assessment#1]
'{userName}のいいところは優しさです。あなたの優しい雰囲気や立ち振舞に多くの人が癒やされています。'

**Comment by anoriqq** [comment]
これから対応します。

**Comment by show0317sw** [comment]
677d385b58cc2545c8b011550bcdf2f6e640f973 で対応されました。

**Comment by anoriqq** [comment]
677d385b58cc2545c8b011550bcdf2f6e640f973 で対応されました。
